#!/usr/bin/python3
#                          Password list Generator
#                          Written by D3athStalk3r
#   Create password lists to use with hashcat to crack the handshake of UK Routers

def main():

    global password_len
    import string
    import random
    lines = '\n'
    vm_chars = "abcdefghjkmnpqrstuvwxyz"
    sky_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    bt_chars = "abcdef23456789"
    talk_chars = "ABCDEFGHJKMNPQRSTVWXY346789"
    plus_chars = "abcdef0123456789"
    u_input = input("To create password lists choose a number:\n1 = TALKTALK\n2 = SKY\n3 = VIRGIN MEDIA_2g_5g\n"
                    "4 = BT HUB 2-5\n5 -PLUSNETXXXX\n>:")
    if u_input == "1" or "2" or "3":
        password_len = int(8)
    password_count = int(input("How many passwords do you want to create? :"))
    for x in range(password_count):
        passwords = ""
        for y in range(password_len):
            if u_input == "1":
                password_char = random.choice(talk_chars)
                passwords = passwords + password_char
            if u_input == "2":
                password_char = random.choice(sky_chars)
                passwords = passwords + password_char
            if u_input == "3":
                password_char = random.choice(vm_chars)
                passwords = passwords + password_char
            if u_input == "4":
                password_len = int(10)
                password_char = random.choice(bt_chars)
                passwords = passwords + password_char
            if u_input == "5":
                password_len = int(10)
                password_char = random.choice(plus_chars)
                passwords = passwords + password_char
        print(passwords)
#        file_open = open("/home/d3athstalk3r/Desktop/Passwords.txt", 'a')
#        file_open.writelines(passwords + lines)
    start = input("Do you want to continue?\ny Continues - Anything else exits!\n>: ")
    if start == "y":
        main()
    else:
        print("Closing Password Generator")
        exit()


main()
